version: '3.8'

services:
  investment_agent:
    build:
      context: .
     
      dockerfile: Dockerfile 
    
    container_name: investment_research_agent
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: always